server:
  port: 8888
management:
  security:
    enabled: false
encrypt:
  key: abcdef
 # key-store:
   # location: classpath:/testen2.jks
    #password: test123
    #alias: testkey
   # secret: secretke
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahulbiswaser/localconfiguration
          username: rahulbiswaser
          password: Informa8@Tion
          searchPaths: 
          - configserver
          - eureka
          - gatewayApp
  application:
    name: configserver
 
          
          